output_dir: C:\Syncthing\SK_OOP_COURSE\1_PART_MVP\chapter_01\lessons\lesson_001\conspects
template: web
media_mode: embed
theme: light
input:
  path: C:\Syncthing\SK_OOP_COURSE\1_PART_MVP\chapter_01\lessons\lesson_001\conspects\lesson_001_brief_results.md
  source_type: standard
  files_folder: C:\Syncthing\SK_OOP_COURSE\1_PART_MVP\chapter_01\media
formats:
- html
metadata:
  title: ''
  author: ''
  lang: ru
  brand_image: ''
styles:
  highlight_theme: github-dark
  mermaid_theme: neutral
fonts:
  embed: true
  dir: assets/fonts
features:
  toc: true
  toc_depth: 2
  breadcrumbs: true
  code_copy: true
  fullscreen: true
  diff_blocks: true
  callouts: true
  mermaid: true
  plyr: true
advanced:
  pandoc_extra_args: []
  custom_css: []
  custom_js: []
