output_dir: C:\Users\User\Documents\Syncthing\SK_OOP_COURSE\1_PART_MVP\chapter_02\lessons\results
template: web
media_mode: embed
theme: light
input:
  path: C:\Users\User\Documents\Syncthing\SK_OOP_COURSE\1_PART_MVP\chapter_02\lessons\results
  source_type: standard
  files_folder: C:\Users\User\Documents\Syncthing\SK_OOP_COURSE\1_PART_MVP\chapter_02\media
formats:
  - html
metadata:
  title: ""
  author: ""
  lang: ru
  brand_image: ""
styles:
  highlight_theme: github-dark
  mermaid_theme: forest
fonts:
  embed: true
  dir: assets/fonts
features:
  toc: true
  toc_depth: 2
  breadcrumbs: true
  code_copy: true
  fullscreen: true
  diff_blocks: true
  callouts: true
  mermaid: true
  plyr: true
advanced:
  pandoc_extra_args: []
  custom_css: []
  custom_js: []
